### ISSUE TITLE
u finna get that dmca

### ISSUE THREAD

**Issue by sanelkukic** [louisboss99/splatoonhackingpack#1]
hoi m8 i found ash-xml on here
im part of ash team and uh do ya mind taking it off of your repo?
you also have other people's software such as nohash

so my request is:
1) remove ash-xml from here
2) either give credits to the creators of the rest of the software or take it all down
and if you dont wanna do either of the above:
3) catch this dmca

thats was all, enjoy the rest of your day

**Comment by louisboss99** [comment]
done read description should i remove nohash ill remove any requested files

**Comment by sanelkukic** [comment]
ye you're good with me now, other people might ask for their stuff to be taken down but idk
